// Sprite label map (paths adjusted to web assets)
export const SPRITE_LABEL_MAP: Record<string, [string, string]> = {
	'/assets/character/Body/body_001.png': ['001', 'Human'],
	'/assets/character/Arms/arms_001.png': ['001', 'Dainty'],
	'/assets/character/Arms/arms_002.png': ['002', 'Average'],
	'/assets/character/Arms/arms_003.png': ['003', 'Broad'],
	'/assets/character/Ears/ears_000.png': ['000', 'None'],
	'/assets/character/Ears/ears_001.png': ['002', 'Elf'],
	'/assets/character/Ears/ears_002.png': ['003', 'Goblin'],
	'/assets/character/Ears/ears_003.png': ['001', 'Round'],
	'/assets/character/Ears/ears_004.png': ['004', 'Halfling'],
	'/assets/character/Eyes/eyes_001.png': ['001', 'Cat'],
	'/assets/character/Eyes/eyes_002.png': ['003', 'Almond'],
	'/assets/character/Eyes/eyes_003.png': ['005', 'Doe'],
	'/assets/character/Eyes/eyes_004.png': ['007', 'Oval'],
	'/assets/character/Eyes/eyes_005.png': ['009', 'Flat'],
	'/assets/character/Eyes/eyes_006.png': ['011', 'Fox'],
	'/assets/character/Eyes/eyes_007.png': ['013', 'Block'],
	'/assets/character/Eyes/eyes_008.png': ['002', 'High Cat'],
	'/assets/character/Eyes/eyes_009.png': ['004', 'High Almond'],
	'/assets/character/Eyes/eyes_010.png': ['006', 'High Doe'],
	'/assets/character/Eyes/eyes_011.png': ['008', 'High Oval'],
	'/assets/character/Eyes/eyes_012.png': ['010', 'High Flat'],
	'/assets/character/Eyes/eyes_013.png': ['012', 'High Fox'],
	'/assets/character/Eyes/eyes_014.png': ['014', 'High Block'],
	'/assets/character/Horns/horns_000.png': ['000', 'None'],
	'/assets/character/Horns/horns_001.png': ['001', 'Curved'],
	'/assets/character/Horns/horns_002.png': ['002', 'Curled'],
	'/assets/character/Horns/horns_003.png': ['003', 'Antlers'],
	'/assets/character/HairA/haira_001.png': ['007', 'Right Part'],
	'/assets/character/HairA/haira_002.png': ['006', 'Left Part'],
	'/assets/character/HairA/haira_003.png': ['008', 'Middle Part'],
	'/assets/character/HairA/haira_004.png': ['011', 'Straight Bangs'],
	'/assets/character/HairA/haira_005.png': ['009', 'Left Swept'],
	'/assets/character/HairA/haira_006.png': ['010', 'Right Swept'],
	'/assets/character/HairA/haira_007.png': ['015', 'Emo Left'],
	'/assets/character/HairA/haira_008.png': ['016', 'Emo Right'],
	'/assets/character/HairA/haira_009.png': ['002', 'Braid'],
	'/assets/character/HairA/haira_010.png': ['001', 'Buzz'],
	'/assets/character/HairA/haira_011.png': ['013', 'Lifted Left'],
	'/assets/character/HairA/haira_012.png': ['005', 'Sleek'],
	'/assets/character/HairA/haira_013.png': ['012', 'Middle Point'],
	'/assets/character/HairA/haira_014.png': ['003', 'Sleek Left Part'],
	'/assets/character/HairA/haira_015.png': ['004', 'Sleek Right Part'],
	'/assets/character/HairA/haira_016.png': ['014', 'Lifted Right'],
	'/assets/character/HairB/hairb_000.png': ['000', 'No Hair Back'],
	'/assets/character/HairB/hairb_001.png': ['001', 'Bob'],
	'/assets/character/HairB/hairb_002.png': ['002', 'Shoulder'],
	'/assets/character/HairB/hairb_003.png': ['003', 'Long'],
	'/assets/character/HairB/hairb_004.png': ['006', 'Curly Bob'],
	'/assets/character/HairB/hairb_005.png': ['007', 'Curly Long'],
	'/assets/character/HairB/hairb_006.png': ['008', 'Afro'],
	'/assets/character/HairB/hairb_007.png': ['009', 'Afro Sleek'],
	'/assets/character/HairB/hairb_008.png': ['019', 'Twin Bun'],
	'/assets/character/HairB/hairb_009.png': ['020', 'Twin Poof'],
	'/assets/character/HairB/hairb_010.png': ['018', 'High Bun'],
	'/assets/character/HairB/hairb_011.png': ['010', 'High Wide Ponytail'],
	'/assets/character/HairB/hairb_012.png': ['015', 'Low Pigtails'],
	'/assets/character/HairB/hairb_013.png': ['014', 'High Pigtails'],
	'/assets/character/HairB/hairb_014.png': ['017', 'Right Braid'],
	'/assets/character/HairB/hairb_015.png': ['004', 'Over Shoulder Left'],
	'/assets/character/HairB/hairb_016.png': ['011', 'Ponytail'],
	'/assets/character/HairB/hairb_017.png': ['016', 'Left Braid'],
	'/assets/character/HairB/hairb_018.png': ['005', 'Over Shoulder Right'],
	'/assets/character/HairB/hairb_019.png': ['012', 'Left Pony'],
	'/assets/character/HairB/hairb_020.png': ['013', 'Right Pony'],
	'/assets/character/HairC/hairc_000.png': ['000', 'No Hair Side'],
	'/assets/character/HairC/hairc_001.png': ['001', 'Short Dangles'],
	'/assets/character/HairC/hairc_002.png': ['002', 'Long Dangles'],
	'/assets/character/HairC/hairc_003.png': ['016', 'Over Both Ears'],
	'/assets/character/HairC/hairc_004.png': ['017', 'Over Left Ear'],
	'/assets/character/HairC/hairc_005.png': ['018', 'Over Right Ear'],
	'/assets/character/HairC/hairc_006.png': ['013', 'Side Swoop Right'],
	'/assets/character/HairC/hairc_007.png': ['020', 'Twin Bun'],
	'/assets/character/HairC/hairc_008.png': ['021', 'Twin Poof'],
	'/assets/character/HairC/hairc_009.png': ['019', 'High Bun'],
	'/assets/character/HairC/hairc_010.png': ['006', 'Fringe Right'],
	'/assets/character/HairC/hairc_011.png': ['005', 'Fringe Left'],
	'/assets/character/HairC/hairc_012.png': ['007', 'Fringe Both'],
	'/assets/character/HairC/hairc_013.png': ['004', 'Fringe Right Long'],
	'/assets/character/HairC/hairc_014.png': ['009', 'Bed Head Right'],
	'/assets/character/HairC/hairc_015.png': ['011', 'Spikey Top Right'],
	'/assets/character/HairC/hairc_016.png': ['015', 'Spikey Right'],
	'/assets/character/HairC/hairc_017.png': ['012', 'Side Swoop Left'],
	'/assets/character/HairC/hairc_018.png': ['003', 'Fringe Left Long'],
	'/assets/character/HairC/hairc_019.png': ['008', 'Bed Head Left'],
	'/assets/character/HairC/hairc_020.png': ['010', 'Spikey Top Left'],
	'/assets/character/HairC/hairc_021.png': ['014', 'Spikey Left'],
	'/assets/character/HairC/hairc_022.png': ['005', 'Fringe Both Long'],
	'/assets/character/Eyebrows/eyebrows_000.png': ['000', 'No Eyebrow'],
	'/assets/character/Eyebrows/eyebrows_001.png': ['001', 'Straight Mid'],
	'/assets/character/Eyebrows/eyebrows_002.png': ['002', 'Straight High'],
	'/assets/character/Eyebrows/eyebrows_003.png': ['003', 'Straight Low'],
	'/assets/character/Eyebrows/eyebrows_004.png': ['004', 'Dot Mid'],
	'/assets/character/Eyebrows/eyebrows_005.png': ['005', 'Dot High'],
	'/assets/character/Eyebrows/eyebrows_006.png': ['006', 'Dot Low'],
	'/assets/character/Face/face_000.png': ['000', 'No Face Addition'],
	'/assets/character/Face/face_001.png': ['001', 'Blush'],
	'/assets/character/Face/face_002.png': ['002', 'Goatee'],
	'/assets/character/Face/face_003.png': ['003', 'Beard'],
	'/assets/character/TopA/topa_001.png': ['001', 'Crew'],
	'/assets/character/TopA/topa_002.png': ['002', 'Turtle'],
	'/assets/character/TopA/topa_003.png': ['004', 'Swoop'],
	'/assets/character/TopA/topa_004.png': ['003', 'Collared'],
	'/assets/character/TopA/topa_005.png': ['005', 'Crop'],
	'/assets/character/TopA/topa_006.png': ['006', 'Strapless'],
	'/assets/character/TopA/topa_007.png': ['007', 'Strapless Crop'],
	'/assets/character/TopA/topa_008.png': ['009', 'Linen Right'],
	'/assets/character/TopA/topa_009.png': ['008', 'Linen Left'],
	'/assets/character/TopA/topa_010.png': ['010', 'Striped'],
	'/assets/character/TopA/topa_011.png': ['011', 'Tank Combo'],
	// "/assets/character/TopA/topa_012.png": ["0XX", "TBA"],
	'/assets/character/TopB/topb_000.png': ['000', 'Sleeveless'],
	'/assets/character/TopB/topb_001.png': ['001', 'Straps'],
	'/assets/character/TopB/topb_002.png': ['002', 'Short'],
	'/assets/character/TopB/topb_003.png': ['003', 'Long'],
	'/assets/character/TopB/topb_004.png': ['004', 'Rolled Cuff'],
	'/assets/character/TopB/topb_005.png': ['008', 'Long Poof'],
	'/assets/character/TopB/topb_006.png': ['006', 'Off Shoulder S. Poof'],
	'/assets/character/TopB/topb_007.png': ['007', 'Off Shoulder L. Poof'],
	'/assets/character/TopB/topb_008.png': ['001', 'Straps'],
	'/assets/character/TopB/topb_009.png': ['002', 'Short'],
	'/assets/character/TopB/topb_010.png': ['003', 'Long'],
	'/assets/character/TopB/topb_011.png': ['004', 'Rolled Cuff'],
	'/assets/character/TopB/topb_012.png': ['008', 'Long Poof'],
	'/assets/character/TopB/topb_013.png': ['006', 'Off Shoulder S. Poof'],
	'/assets/character/TopB/topb_014.png': ['007', 'Off Shoulder L. Poof'],
	'/assets/character/TopB/topb_015.png': ['001', 'Straps'],
	'/assets/character/TopB/topb_016.png': ['002', 'Short'],
	'/assets/character/TopB/topb_017.png': ['003', 'Long'],
	'/assets/character/TopB/topb_018.png': ['004', 'Rolled Cuff'],
	'/assets/character/TopB/topb_019.png': ['008', 'Long Poof'],
	'/assets/character/TopB/topb_020.png': ['006', 'Off Shoulder S. Poof'],
	'/assets/character/TopB/topb_021.png': ['007', 'Off Shoulder L. Poof'],
	'/assets/character/TopB/topb_022.png': ['005', 'Long Cuff'],
	'/assets/character/TopB/topb_023.png': ['005', 'Long Cuff'],
	'/assets/character/TopB/topb_024.png': ['005', 'Long Cuff'],
	'/assets/character/TopB/topb_025.png': ['009', 'Long Combo Black'],
	'/assets/character/TopB/topb_026.png': ['009', 'Long Combo Black'],
	'/assets/character/TopB/topb_027.png': ['009', 'Long Combo Black'],
	'/assets/character/TopB/topb_028.png': ['010', 'Long Combo White'],
	'/assets/character/TopB/topb_029.png': ['010', 'Long Combo White'],
	'/assets/character/TopB/topb_030.png': ['010', 'Long Combo White'],
	'/assets/character/Mid/mid_000.png': ['000', 'None'],
	'/assets/character/Mid/mid_001.png': ['001', 'Waist Apron'],
	'/assets/character/Mid/mid_002.png': ['002', 'Leather Corset'],
	'/assets/character/Mid/mid_003.png': ['003', 'Chunky Belt Left'],
	'/assets/character/Mid/mid_004.png': ['005', 'Thin Belt'],
	'/assets/character/Mid/mid_005.png': ['004', 'Chunky Belt Right'],
	'/assets/character/JacketA/jacketa_000.png': ['000', 'No Jacket'],
	'/assets/character/JacketA/jacketa_001.png': ['001', 'Chunky Closed'],
	'/assets/character/JacketA/jacketa_002.png': ['002', 'Chunky Open'],
	'/assets/character/JacketA/jacketa_003.png': ['003', 'Fitted Closed'],
	'/assets/character/JacketA/jacketa_004.png': ['004', 'Fitted Open'],
	'/assets/character/JacketA/jacketa_005.png': ['005', 'Sweater'],
	'/assets/character/JacketA/jacketa_006.png': ['006', 'Buttoned'],
	'/assets/character/JacketA/jacketa_007.png': ['009', 'Cropped'],
	'/assets/character/JacketA/jacketa_008.png': ['007', 'Long'],
	'/assets/character/JacketA/jacketa_009.png': ['008', 'Cropped Closed'],
	'/assets/character/JacketB/jacketb_000.png': ['000', 'No Jacket Sleeves'],
	'/assets/character/JacketB/jacketb_001.png': ['003', 'Chunky Sleeve'],
	'/assets/character/JacketB/jacketb_002.png': ['002', 'Fitted Sleeve'],
	'/assets/character/JacketB/jacketb_003.png': ['003', 'Chunky Sleeve'],
	'/assets/character/JacketB/jacketb_004.png': ['002', 'Fitted Sleeve'],
	'/assets/character/JacketB/jacketb_005.png': ['003', 'Chunky Sleeve'],
	'/assets/character/JacketB/jacketb_006.png': ['002', 'Fitted Sleeve'],
	'/assets/character/JacketB/jacketb_007.png': ['001', 'Short Sleeve'],
	'/assets/character/JacketB/jacketb_008.png': ['001', 'Short Sleeve'],
	'/assets/character/JacketB/jacketb_009.png': ['001', 'Short Sleeve'],
	'/assets/character/Gloves/gloves_000.png': ['000', 'No Gloves'],
	'/assets/character/Gloves/gloves_001.png': ['001', 'Work Gloves'],
	'/assets/character/BottomA/bottoma_001.png': ['003', 'Pants'],
	'/assets/character/BottomA/bottoma_002.png': ['002', 'Rolled Pants'],
	'/assets/character/BottomA/bottoma_003.png': ['001', 'Shorts'],
	'/assets/character/BottomA/bottoma_004.png': ['006', 'Short Skirt'],
	'/assets/character/BottomA/bottoma_005.png': ['005', 'Pencil Skirt'],
	'/assets/character/BottomA/bottoma_006.png': ['007', 'Long Skirt'],
	'/assets/character/BottomA/bottoma_007.png': ['004', 'Wide Pants'],
	'/assets/character/BottomB/bottomb_000.png': ['000', 'No Waist'],
	'/assets/character/BottomB/bottomb_001.png': ['001', 'Belt Buckle'],
	'/assets/character/BottomB/bottomb_002.png': ['002', 'Belt'],
	'/assets/character/BottomB/bottomb_003.png': ['003', 'Mid Waist'],
	'/assets/character/BottomB/bottomb_004.png': ['005', 'Button Suspenders'],
	'/assets/character/BottomB/bottomb_005.png': ['006', 'Suspenders'],
	'/assets/character/BottomB/bottomb_006.png': ['007', 'Low Overalls'],
	'/assets/character/BottomB/bottomb_007.png': ['008', 'Button Overalls'],
	'/assets/character/BottomB/bottomb_008.png': ['009', 'Overalls'],
	'/assets/character/BottomB/bottomb_009.png': ['004', 'High Waist'],
	'/assets/character/Socks/socks_000.png': ['000', 'No Socks'],
	'/assets/character/Socks/socks_001.png': ['001', 'Short'],
	'/assets/character/Socks/socks_002.png': ['002', 'Thigh'],
	'/assets/character/Socks/socks_003.png': ['003', 'Tights'],
	'/assets/character/Shoes/shoes_001.png': ['003', 'Closed'],
	'/assets/character/Shoes/shoes_002.png': ['002', 'Toe Hole'],
	'/assets/character/Shoes/shoes_003.png': ['004', 'Boot'],
	'/assets/character/Shoes/shoes_004.png': ['001', 'Flat'],
	'/assets/character/AccessoryA/accessorya_000.png': ['000', 'No Face Accessory'],
	'/assets/character/AccessoryA/accessorya_001.png': ['002', 'Circle Rim'],
	'/assets/character/AccessoryA/accessorya_002.png': ['001', 'Rectangle Rim'],
	'/assets/character/AccessoryA/accessorya_003.png': ['004', 'Circle Monocle Left'],
	'/assets/character/AccessoryA/accessorya_004.png': ['003', 'Rect. Monocle Left'],
	'/assets/character/AccessoryA/accessorya_005.png': ['006', 'Circle Monocle Right'],
	'/assets/character/AccessoryA/accessorya_006.png': ['005', 'Rect. Monocle Right'],
	'/assets/character/AccessoryB/accessoryb_000.png': ['000', 'No Head Accessory'],
	'/assets/character/AccessoryB/accessoryb_001.png': ['001', 'Left Bow'],
	'/assets/character/AccessoryB/accessoryb_002.png': ['005', 'Bandana'],
	'/assets/character/AccessoryB/accessoryb_003.png': ['003', 'Top Bow'],
	'/assets/character/AccessoryB/accessoryb_004.png': ['008', 'Bunny Ears'],
	'/assets/character/AccessoryB/accessoryb_005.png': ['006', 'Snapback'],
	'/assets/character/AccessoryB/accessoryb_006.png': ['007', 'Baseball Cap'],
	'/assets/character/AccessoryB/accessoryb_007.png': ['004', 'Headband'],
	'/assets/character/AccessoryB/accessoryb_008.png': ['002', 'Right Bow'],
	'/assets/character/AccessoryB/accessoryb_009.png': ['009', 'Cat Ears'],
	'/assets/character/AccessoryB/accessoryb_010.png': ['010', 'Fox Ears'],
	'/assets/character/AccessoryC/accessoryc_000.png': ['000', 'No Neck Accessory'],
	'/assets/character/AccessoryC/accessoryc_001.png': ['007', 'Hood'],
	'/assets/character/AccessoryC/accessoryc_002.png': ['003', 'Neck Ribbon Collar'],
	'/assets/character/AccessoryC/accessoryc_003.png': ['001', 'Choker'],
	'/assets/character/AccessoryC/accessoryc_004.png': ['009', 'Fur Collar'],
	'/assets/character/AccessoryC/accessoryc_005.png': ['008', 'Doll Collar'],
	'/assets/character/AccessoryC/accessoryc_006.png': ['005', 'Tie Collar'],
	'/assets/character/AccessoryC/accessoryc_007.png': ['004', 'Neck Ribbon'],
	'/assets/character/AccessoryC/accessoryc_008.png': ['006', 'Tie'],
	'/assets/character/AccessoryC/accessoryc_009.png': ['002', 'Shirt Collar'],
	'/assets/character/AccessoryD/accessoryd_000.png': ['000', 'No Head Accessory'],
	'/assets/character/AccessoryD/accessoryd_001.png': ['001', 'Left Bow'],
	'/assets/character/AccessoryD/accessoryd_002.png': ['005', 'Bandana'],
	'/assets/character/AccessoryD/accessoryd_003.png': ['003', 'Top Bow'],
	'/assets/character/AccessoryD/accessoryd_004.png': ['008', 'Bunny Ears'],
	'/assets/character/AccessoryD/accessoryd_005.png': ['006', 'Snapback'],
	'/assets/character/AccessoryD/accessoryd_006.png': ['007', 'Baseball Cap'],
	'/assets/character/AccessoryD/accessoryd_007.png': ['004', 'Headband'],
	'/assets/character/AccessoryD/accessoryd_008.png': ['002', 'Right Bow'],
	'/assets/character/AccessoryD/accessoryd_009.png': ['009', 'Cat Ears'],
	'/assets/character/AccessoryD/accessoryd_010.png': ['010', 'Cat Ears'],
	'/assets/character/ShoulderA/shouldera_000.png': ['000', 'None'],
	'/assets/character/ShoulderA/shouldera_001.png': ['001', 'Cloak'],
	'/assets/character/ShoulderA/shouldera_002.png': ['002', 'Backpack'],
	'/assets/character/ShoulderA/shouldera_003.png': ['003', 'Pauldron'],
	'/assets/character/BackA/backa_000.png': ['000', 'None'],
	'/assets/character/BackA/backa_001.png': ['001', 'Butterfly'],
	'/assets/character/BackA/backa_002.png': ['002', 'Lined Butterfly'],
	'/assets/character/ChopA/chopa_000.png': ['000', 'No Tool'],
	'/assets/character/ChopA/chopa_001.png': ['001', 'Axe'],
	'/assets/character/Water/water_000.png': ['000', 'No Tool'],
	'/assets/character/Water/water_001.png': ['001', 'Watering Can'],
	'/assets/character/StrikeA/strikea_000.png': ['000', 'No Tool'],
	'/assets/character/StrikeA/strikea_001.png': ['001', 'Pickaxe'],
	'/assets/character/StrikeA/strikea_002.png': ['002', 'Hoe'],
	'/assets/character/StrikeA/strikea_003.png': ['003', 'Axe'],
	'/assets/character/Seed/seed_000.png': ['000', 'No Tool'],
	'/assets/character/Seed/seed_001.png': ['001', 'Seed Bag'],
	'/assets/character/Reap/reap_000.png': ['000', 'No Tool'],
	'/assets/character/Reap/reap_001.png': ['001', 'Scythe'],
};

export function getSpriteLabel(url: string): [string, string] | undefined {
	return SPRITE_LABEL_MAP[url] ?? undefined;
}
