import type {Category, SpriteLayer} from './types';

// Canonical list of all renderable sprite layers in child order.
export const SPRITE_LAYERS: SpriteLayer[] = [
	'Body',
	'Head',
	'Arms',
	'BottomA',
	'BottomB',
	'TopA',
	'TopB',
	'HairA',
	'HairB',
	'HairC',
	'HairD',
	'AccessoryA',
	'AccessoryB',
	'AccessoryC',
	'AccessoryD',
	'JacketA',
	'JacketB',
	'Shoes',
	'Socks',
	'Gloves',
	'Eyes',
	'Eyebrows',
	'Face',
	'Ears',
	'Horns',
	'Mid',
	'BackA',
	'BackB',
	'ShoulderA',
	'ShoulderB',
	'ChopA',
	'ChopB',
	'StrikeA',
	'StrikeB',
	'Reap',
	'Water',
	'Seed',
];

// SpriteHolder child order — determines tie-breaking when z-indices match.
export const SPRITE_ORDER: SpriteLayer[] = [
	'AccessoryA',
	'AccessoryB',
	'AccessoryC',
	'AccessoryD',
	'Arms',
	'Body',
	'BottomA',
	'BottomB',
	'Eyes',
	'HairA',
	'HairB',
	'HairC',
	'HairD',
	'Head',
	'JacketA',
	'JacketB',
	'Shoes',
	'Socks',
	'TopA',
	'TopB',
	'BackA',
	'BackB',
	'ShoulderA',
	'ShoulderB',
	'Ears',
	'Eyebrows',
	'Face',
	'Gloves',
	'Horns',
	'Mid',
	'StrikeA',
	'StrikeB',
	'ChopA',
	'ChopB',
	'Water',
	'Reap',
	'Seed',
];

// Categories whose asset files start at _000 (zero-indexed).
export const ZERO_INDEXED_CATEGORIES = new Set<Category>([
	'AccessoryA',
	'AccessoryB',
	'AccessoryC',
	'AccessoryD',
	'BackA',
	'BackB',
	'BottomB',
	'ChopA',
	'ChopB',
	'Ears',
	'Eyebrows',
	'Face',
	'Gloves',
	'HairB',
	'HairC',
	'HairD',
	'Horns',
	'JacketA',
	'JacketB',
	'Mid',
	'Reap',
	'Seed',
	'ShoulderA',
	'ShoulderB',
	'Socks',
	'StrikeA',
	'StrikeB',
	'TopB',
	'Water',
]);

// Primary → secondary sprite mirror pairs.
export const SECONDARY_MIRROR_MAP: Partial<Record<Category, Category>> = {
	BackA: 'BackB',
	ShoulderA: 'ShoulderB',
	ChopA: 'ChopB',
	StrikeA: 'StrikeB',
	HairB: 'HairD',
};

// Secondary-only layers driven by their primary counterpart.
export const SECONDARY_ONLY_LAYERS = new Set<SpriteLayer>([
	'HairD',
	'BackB',
	'ShoulderB',
	'ChopB',
	'StrikeB',
]);

// Resolve the asset filename for a category (handles irregular naming).
const FILE_NAME_OVERRIDES: Partial<Record<Category, string>> = {
	Eyes: 'eyes',
	Eye: 'eyes',
	Body: 'body',
	Skintone: 'body',
	Head: 'head',
	Face: 'face',
	Hair: 'haira',
	HairA: 'haira',
};

export function resolveFileName(category: Category): string {
	return FILE_NAME_OVERRIDES[category] ?? category.toLowerCase();
}
