// THE PROFILE TABLE IS DATA, and this is what keeps it that way.
//
// data/prop_profiles.csv is generated by tools/gen_prop_profiles.py into TWO
// files — shaders/prop_profiles.glsl (the rings, read by the vertex stage) and
// src/tables/prop_profiles.h (the vertex counts, read by the draw). Generated-
// and-committed is the right trade, but it has one failure mode: somebody
// edits a generated file, or edits the CSV and forgets to re-run, and the two
// quietly disagree.
//
// AND HERE THAT DISAGREEMENT IS WORSE THAN A WRONG COLOUR. The vertex count is
// a FUNCTION of segments and rings; if the shader's rings and the engine's
// count ever drift apart, every prop in the world loses its last ring — or
// draws a ring that is not there — and nothing fails to build, nothing throws,
// and the picture merely looks slightly wrong forever.
//
// What it pins:
//   1. every CSV row stands at its own ordinal (ids are append-only);
//   2. a profile spans its prop exactly — first ring at y 0, last at y 1 —
//      and every ring stands above the one below it, because the body is
//      built by walking that list and a reversed pair would turn the mesh
//      inside out;
//   3. the GLSL carries the same segments, ring count, bark line and rings as
//      the CSV, padded to the declared stride;
//   4. the C++ vertex count is EXACTLY what the row's geometry needs:
//      segments × 6 × (rings − 1) + segments × 3.
#include "check.h"

#include "tables/prop_profiles.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

struct Row {
    std::string name;
    int segments = 0;
    float barkTop = 0.0f;
    std::vector<std::pair<float, float>> rings;   // radius, height
};

std::string slurp(const std::string& path) {
    std::ifstream in(path);
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

// The CSV, parsed exactly as the generator parses it — including the quoted
// note, whose commas would otherwise eat the tail of the row.
std::vector<Row> read_csv(const std::string& path, int& headerCols) {
    std::vector<Row> rows;
    std::ifstream in(path);
    std::string line;
    std::vector<std::string> header;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty() || line[0] == '#') continue;
        std::vector<std::string> cells;
        std::string cur;
        bool quoted = false;
        for (const char c : line) {
            if (c == '"') { quoted = !quoted; continue; }
            if (c == ',' && !quoted) { cells.push_back(cur); cur.clear(); }
            else cur.push_back(c);
        }
        cells.push_back(cur);
        if (header.empty()) { header = cells; headerCols = int(cells.size()); continue; }
        auto col = [&](const char* want) -> std::string {
            for (std::size_t i = 0; i < header.size() && i < cells.size(); ++i)
                if (header[i] == want) return cells[i];
            return {};
        };
        Row r;
        r.name = col("name");
        // strtof/strtol, NOT std::stoi/std::stof: exceptions are off in this
        // tree (-fno-exceptions), so a throwing parser does not report a bad
        // cell — it aborts the process, which is how this witness first died.
        r.segments = int(std::strtol(col("segments").c_str(), nullptr, 10));
        r.barkTop = std::strtof(col("bark_top").c_str(), nullptr);
        const std::string rings = col("rings");
        std::size_t pos = 0;
        while (pos < rings.size()) {
            const std::size_t semi = rings.find(';', pos);
            const std::string part = rings.substr(
                pos, semi == std::string::npos ? std::string::npos : semi - pos);
            const std::size_t at = part.find('@');
            if (at != std::string::npos)
                r.rings.emplace_back(
                    std::strtof(part.substr(0, at).c_str(), nullptr),
                    std::strtof(part.substr(at + 1).c_str(), nullptr));
            if (semi == std::string::npos) break;
            pos = semi + 1;
        }
        rows.push_back(r);
    }
    return rows;
}

// Pull every `vec2(a, b)` / bare number out of a named GLSL array initialiser.
std::vector<float> glsl_numbers(const std::string& glsl, const std::string& name) {
    std::vector<float> out;
    const std::size_t at = glsl.find(name);
    if (at == std::string::npos) return out;
    // The initialiser's own parenthesis — `uint[2](` / `vec2[12](` carry
    // exactly one, and looking for a second was this witness's first bug.
    const std::size_t open = glsl.find('(', at);
    const std::size_t close = open == std::string::npos
                                  ? std::string::npos
                                  : glsl.find(");", open);
    if (open == std::string::npos || close == std::string::npos) return out;
    const std::string body = glsl.substr(open, close - open);
    std::string num;
    bool inIdent = false;   // `vec2` ends in a DIGIT — see below
    for (std::size_t i = 0; i < body.size(); ++i) {
        const char c = body[i];
        // `//` comments carry ordinals and row names; skip the line outright
        // so a profile's own index is never read as data.
        if (c == '/' && i + 1 < body.size() && body[i + 1] == '/') {
            if (!num.empty() && !inIdent)
                out.push_back(std::strtof(num.c_str(), nullptr));
            num.clear();
            inIdent = false;
            const std::size_t nl = body.find('\n', i);
            if (nl == std::string::npos) break;
            i = nl;
            continue;
        }
        const bool alpha = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                        || c == '_';
        const bool digit = (c >= '0' && c <= '9') || c == '.' || c == '-';
        // A DIGIT GLUED TO A NAME IS PART OF THE NAME. This witness first read
        // the `2` of every `vec2(` as a ring radius, and the table it compared
        // against was therefore shifted by one number per row — the kind of
        // wrong that looks like a real disagreement and is not.
        if (alpha) {
            // A LETTER BEFORE DIGITS OPENS A NAME; a letter AFTER them is a
            // SUFFIX (`6u`, `1.0f`) and the number is already complete. The
            // first version of this threw away every `6u` in the table and
            // then complained that the row counts disagreed.
            if (!num.empty() && !inIdent) {
                out.push_back(std::strtof(num.c_str(), nullptr));
                num.clear();
            } else {
                num.clear();
            }
            inIdent = true;
            continue;
        }
        if (digit) { num.push_back(c); continue; }
        if (!num.empty() && !inIdent)
            out.push_back(std::strtof(num.c_str(), nullptr));
        num.clear();
        inIdent = false;
    }
    if (!num.empty() && !inIdent)
        out.push_back(std::strtof(num.c_str(), nullptr));
    return out;
}

constexpr float kEps = 1e-4f;

} // namespace

int main() {
    using namespace sm;
    using namespace sm::test;

    const std::string root = TIMAERT_REPO_DIR;
    int headerCols = 0;
    const std::vector<Row> rows = read_csv(root + "/data/prop_profiles.csv",
                                           headerCols);
    const std::string glsl = slurp(root + "/shaders/prop_profiles.glsl");

    CHECK(!rows.empty(), "таблица профилей читается из CSV");
    CHECK(!glsl.empty(), "сгенерированный GLSL читается");
    CHECK(int(rows.size()) == kPropProfileCount,
          "счёт строк CSV и счёт в сгенерированном заголовке — одно число");

    // ── 2. A PROFILE SPANS ITS PROP, AND ITS RINGS CLIMB ──────────────────
    int climbs = 0;
    for (const Row& r : rows) {
        CHECK(r.rings.size() >= 2, "у профиля есть хотя бы два яруса");
        CHECK(std::fabs(r.rings.front().second) < kEps
                  && std::fabs(r.rings.back().second - 1.0f) < kEps,
              "профиль покрывает проп ровно: низ на 0, верх на 1");
        for (std::size_t k = 1; k < r.rings.size(); ++k) {
            CHECK(r.rings[k].second > r.rings[k - 1].second,
                  "каждый ярус стоит ВЫШЕ предыдущего — перевёрнутая пара "
                  "вывернула бы тело наизнанку");
            ++climbs;
        }
        CHECK(r.barkTop >= 0.0f && r.barkTop <= 1.0f,
              "граница коры лежит внутри высоты пропа");
        CHECK(r.segments >= 3 && r.segments <= 32,
              "у тела вращения от трёх до тридцати двух сторон");
    }
    CHECK(climbs > 0, "ярусы вообще проверялись");

    // ── 3. THE GLSL IS THE CSV ────────────────────────────────────────────
    const std::vector<float> segs = glsl_numbers(glsl, "kProfileSegments[");
    const std::vector<float> ringN = glsl_numbers(glsl, "kProfileRingCount[");
    const std::vector<float> bark = glsl_numbers(glsl, "kProfileBarkTop[");
    const std::vector<float> rings = glsl_numbers(glsl, "kProfileRings[");
    CHECK(segs.size() == rows.size() && ringN.size() == rows.size()
              && bark.size() == rows.size(),
          "в GLSL столько же строк сегментов, ярусов и коры, сколько в CSV");
    int cells = 0;
    for (std::size_t i = 0; i < rows.size() && i < segs.size(); ++i) {
        CHECK(int(segs[i]) == rows[i].segments,
              "сегменты строки в GLSL — те, что в CSV");
        CHECK(std::size_t(ringN[i]) == rows[i].rings.size(),
              "счёт ярусов в GLSL — тот, что в CSV");
        CHECK(std::fabs(bark[i] - rows[i].barkTop) < kEps,
              "граница коры в GLSL — та, что в CSV");
        ++cells;
    }
    CHECK(cells == int(rows.size()), "сверены ВСЕ строки, а не часть");

    // Rings ride a padded stride so the shader can index them with a runtime
    // profile id; the padding repeats the last ring, which is what makes an
    // over-read degenerate instead of reaching into the next profile.
    const std::size_t stride = rows.empty() ? 0
                                            : rings.size() / 2 / rows.size();
    CHECK(stride >= 2, "шаг таблицы ярусов в GLSL осмыслен");
    int ringChecks = 0;
    for (std::size_t i = 0; i < rows.size(); ++i) {
        for (std::size_t k = 0; k < stride; ++k) {
            const std::size_t at = (i * stride + k) * 2;
            if (at + 1 >= rings.size()) break;
            const auto& want = k < rows[i].rings.size() ? rows[i].rings[k]
                                                        : rows[i].rings.back();
            CHECK(std::fabs(rings[at] - want.first) < kEps
                      && std::fabs(rings[at + 1] - want.second) < kEps,
                  "ярус в GLSL — тот, что в CSV (хвост повторяет последний)");
            ++ringChecks;
        }
    }
    CHECK(ringChecks >= int(rows.size() * 2),
          "ярусы сверялись, а не пропускались молча");

    // ── 4. THE VERTEX COUNT IS THE GEOMETRY'S OWN ─────────────────────────
    // Re-derived here rather than copied: quads between every pair of rings,
    // plus one fan cap. This is the number the draw uses, and it is the one
    // that fails silently.
    for (std::size_t i = 0; i < rows.size() && i < std::size_t(kPropProfileCount); ++i) {
        const std::uint32_t want =
            std::uint32_t(rows[i].segments) * 6u
                * std::uint32_t(rows[i].rings.size() - 1)
            + std::uint32_t(rows[i].segments) * 3u;
        CHECK(kPropProfileVertices[i] == want,
              "счёт вершин профиля ВЫВЕДЕН из его же строки: сегменты × 6 × "
              "(ярусов − 1) + шапка");
    }

    std::printf("  [замер] профилей %d, ярусов в самом богатом %zu, "
                "вершин у ближнего дерева %u\n",
                kPropProfileCount,
                rows.empty() ? 0u : rows.front().rings.size(),
                kPropProfileVertices[0]);
    return report("prop_profile_test");
}
