// GENERATED by tools/gen_prop_profiles.py from
// data/prop_profiles.csv — do not hand-edit. Edit the CSV and
// re-run; `prop_profile_test` re-derives this file and fails on
// drift.
//
// The CPU half of the profile table. The engine does not build the
// body — the vertex stage does, out of shaders/prop_profiles.glsl —
// so what it needs from a row is exactly two things: how many
// vertices one draw of this profile takes, and (for the renderer's
// own bookkeeping) what the row is called. Both are DERIVED from
// the same CSV line the shader reads, which is why they cannot
// drift apart: a hand-kept vertex count would be one careless edit
// away from dropping the last ring of every tree in the world, and
// nothing would fail to compile.
#pragma once

#include <cstdint>

namespace sm {

enum class PropProfile : std::uint8_t {
    TreeConifer = 0,
    TreeBroadleaf = 1,
    TreePalm = 2,
    TreeScrub = 3,
    TreeFar = 4,
};

inline constexpr int kPropProfileCount = 5;

// Vertices one draw of this profile takes: `segments` quads
// between every pair of rings, plus a fan cap on top.
inline constexpr std::uint32_t kPropProfileVertices[kPropProfileCount] = {
    99u,  // 0 tree_conifer — 3 segments × 1 ring gaps + cap
    108u,  // 1 tree_broadleaf — 4 segments × 2 ring gaps + cap
    57u,  // 2 tree_palm — 3 segments × 1 ring gaps + cap
    63u,  // 3 tree_scrub — 3 segments × 1 ring gaps + cap
    51u,  // 4 tree_far — 3 segments × 1 ring gaps + cap
};

} // namespace sm
