// GENERATED by tools/gen_prop_profiles.py from
// data/prop_profiles.csv — do not hand-edit. Edit the CSV and
// re-run; `prop_profile_test` re-derives this file and fails on
// drift.
//
// The CPU half of the profile table. The engine does not build the
// body — the vertex stage does, out of shaders/prop_profiles.glsl —
// so what it needs from a row is exactly two things: how many
// vertices one draw of this profile takes, and (for the renderer's
// own bookkeeping) what the row is called. Both are DERIVED from
// the same CSV line the shader reads, which is why they cannot
// drift apart: a hand-kept vertex count would be one careless edit
// away from dropping the last ring of every tree in the world, and
// nothing would fail to compile.
#pragma once

#include <cstdint>

namespace sm {

enum class PropProfile : std::uint8_t {
    TreeNear = 0,
    TreeFar = 1,
};

inline constexpr int kPropProfileCount = 2;

// Vertices one draw of this profile takes: `segments` quads
// between every pair of rings, plus a fan cap on top.
inline constexpr std::uint32_t kPropProfileVertices[kPropProfileCount] = {
    162u,  // 0 tree_near — 6 segments × 4 ring gaps + cap
    84u,  // 1 tree_far — 4 segments × 3 ring gaps + cap
};

} // namespace sm
