// GENERATED by tools/gen_ground_table.py from
// data/ground_materials.csv + data/ground_cover.csv — do not
// hand-edit. Edit the CSV and re-run it; the `ground_table_test`
// ctest re-derives this file from the CSVs and fails on drift.
//
// Included by shaders/mesh.frag, the one shader that draws the
// subworld ground. The shader holds the procedural SHAPES (the
// families below); every NUMBER lives here, from the CSV.
#ifndef TIMAERT_GROUND_SURFACE
#define TIMAERT_GROUND_SURFACE

// Procedural shape families — the id space of the `family`
// column. A family is a SHAPE; materials sharing one differ
// only by the numbers in their row.
const uint kGfSoil = 0u;
const uint kGfTurf = 1u;
const uint kGfSand = 2u;
const uint kGfFurrow = 3u;
const uint kGfStone = 4u;
const uint kGfTrack = 5u;
const uint kGfMud = 6u;

// Row count. mesh.frag clamps the sampled material id against
// this: an out-of-range const-array read is undefined in GLSL,
// and the id arrives from a texture byte.
const uint kGroundCount = 15u;
const uint kCoverCount = 4u;

//  0 tundra    turf    CV 0.16/0.20  meso 1.20 m  grain 0.05 m  relief 0.090 m  cover grass 0.35
//    lichen mat over frozen ground — low tussocks and sparse cover
//  1 taiga     turf    CV 0.22/0.24  meso 0.90 m  grain 0.04 m  relief 0.120 m  cover grass 0.60
//    needle litter and moss between the trunks
//  2 snow      soil    CV 0.07/0.05  meso 2.00 m  grain 0.06 m  relief 0.050 m  cover snow 1.00
//    the GROUND of the snow biome is frozen earth — the white is COVER at
//    density 1; take the cover away and the ground underneath is honest
//  3 valley    soil    CV 0.18/0.20  meso 1.40 m  grain 0.05 m  relief 0.080 m  cover grass 0.45
//    dry river-valley loam
//  4 meadow    turf    CV 0.20/0.22  meso 0.80 m  grain 0.04 m  relief 0.100 m  cover grass 0.75
//    the default ground of the temperate world
//  5 swamp     mud     CV 0.24/0.24  meso 1.60 m  grain 0.05 m  relief 0.070 m  cover grass 0.50
//    peat flats with standing water — reeds where it drains
//  6 desert    sand    CV 0.10/0.10  meso 1.10 m  grain 0.03 m  relief 0.100 m  cover none 0.00
//    wind ripples are the whole structure of a dune field
//  7 steppe    turf    CV 0.19/0.22  meso 1.00 m  grain 0.04 m  relief 0.100 m  cover grass 0.50
//    dry bunch grass over pale loess
//  8 tropics   turf    CV 0.26/0.26  meso 0.70 m  grain 0.04 m  relief 0.120 m  cover grass 0.90
//    closed herb layer — the ground barely shows
//  9 field     furrow  CV 0.20/0.14  meso 4.50 m  grain 0.04 m  relief 0.140 m  cover grass 0.25
//    ridge-and-furrow: one ridge pair every meso_m (4.5 m is the historic
//    strip width) with ploughed lines eight to the ridge; rows run
//    EAST-WEST — the north-south twin is id 14 and the pick is
//    field_furrows_vertical (sub/material.h)
// 10 shore     sand    CV 0.12/0.12  meso 0.90 m  grain 0.03 m  relief 0.070 m  cover none 0.00
//    wave-combed sand; damp 1 = the band below the shoreline reads wet
// 11 rock      stone   CV 0.15/0.20  meso 2.20 m  grain 0.06 m  relief 0.220 m  cover moss 0.18
//    bare massif — plates split by cracks, moss only along the joints
// 12 road      track   CV 0.14/0.10  meso 3.00 m  grain 0.03 m  relief 0.040 m  cover none 0.00
//    packed dirt and gravel — the surface a thousand feet made flat
// 13 waterbed  mud     CV 0.13/0.14  meso 1.30 m  grain 0.05 m  relief 0.050 m  cover none 0.00
//    lake and river bed, seen through the water plane
// 14 field_v   furrow  CV 0.20/0.14  meso 4.50 m  grain 0.04 m  relief 0.140 m  cover grass 0.25
//    the same ploughed field as id 9 with the ridges running NORTH-SOUTH

// Mean linear colour of the unlit ground.
const vec3 kGroundAlbedo[15] = vec3[15](
    vec3(0.50000, 0.52000, 0.45000),  //  0 tundra
    vec3(0.22000, 0.38000, 0.28000),  //  1 taiga
    vec3(0.62000, 0.66000, 0.70000),  //  2 snow
    vec3(0.55000, 0.52000, 0.32000),  //  3 valley
    vec3(0.40000, 0.52000, 0.28000),  //  4 meadow
    vec3(0.24000, 0.36000, 0.20000),  //  5 swamp
    vec3(0.82000, 0.72000, 0.48000),  //  6 desert
    vec3(0.68000, 0.60000, 0.32000),  //  7 steppe
    vec3(0.12000, 0.36000, 0.12000),  //  8 tropics
    vec3(0.55000, 0.48000, 0.26000),  //  9 field
    vec3(0.76000, 0.68000, 0.46000),  // 10 shore
    vec3(0.45000, 0.43000, 0.39000),  // 11 rock
    vec3(0.42000, 0.34000, 0.23000),  // 12 road
    vec3(0.38000, 0.35000, 0.29000),  // 13 waterbed
    vec3(0.55000, 0.48000, 0.26000)   // 14 field_v
);

// Which shape each ground wears.
const uint kGroundFamily[15] = uint[15](
    1u,  //  0 tundra
    1u,  //  1 taiga
    0u,  //  2 snow
    0u,  //  3 valley
    1u,  //  4 meadow
    6u,  //  5 swamp
    2u,  //  6 desert
    1u,  //  7 steppe
    1u,  //  8 tropics
    3u,  //  9 field
    2u,  // 10 shore
    4u,  // 11 rock
    5u,  // 12 road
    6u,  // 13 waterbed
    3u   // 14 field_v
);

// x = lognormal sigma reproducing the row's target luminance CV,
// y = meso structure frequency (cycles per metre, = 1/meso_m),
// z = chroma sigma (lognormal width of the hue drift),
// w = relief height in METRES — the normal-perturbation scale.
const vec4 kGroundSurface[15] = vec4[15](
    vec4(0.15899, 0.83333, 0.06000, 0.09000),  //  0 tundra
    vec4(0.21741, 1.11111, 0.09000, 0.12000),  //  1 taiga
    vec4(0.06991, 0.50000, 0.02000, 0.05000),  //  2 snow
    vec4(0.17857, 0.71429, 0.08000, 0.08000),  //  3 valley
    vec4(0.19804, 1.25000, 0.08000, 0.10000),  //  4 meadow
    vec4(0.23665, 0.62500, 0.10000, 0.07000),  //  5 swamp
    vec4(0.09975, 0.90909, 0.04000, 0.10000),  //  6 desert
    vec4(0.18832, 1.00000, 0.07000, 0.10000),  //  7 steppe
    vec4(0.25576, 1.42857, 0.10000, 0.12000),  //  8 tropics
    vec4(0.19804, 0.22222, 0.07000, 0.14000),  //  9 field
    vec4(0.11957, 1.11111, 0.05000, 0.07000),  // 10 shore
    vec4(0.14917, 0.45455, 0.05000, 0.22000),  // 11 rock
    vec4(0.13932, 0.33333, 0.05000, 0.04000),  // 12 road
    vec4(0.12946, 0.76923, 0.05000, 0.05000),  // 13 waterbed
    vec4(0.19804, 0.22222, 0.07000, 0.14000)   // 14 field_v
);

// Lognormal sigma of the TERRAIN-scale patchwork (from macro_cv).
// The band that survives to the horizon: past a couple of
// hundred metres the pixel footprint has eaten every finer one,
// and this is all that keeps a bare biome from being a flat
// plane of one colour.
const float kGroundMacroSigma[15] = float[15](
    0.19804,  //  0 tundra
    0.23665,  //  1 taiga
    0.04997,  //  2 snow
    0.19804,  //  3 valley
    0.21741,  //  4 meadow
    0.23665,  //  5 swamp
    0.09975,  //  6 desert
    0.21741,  //  7 steppe
    0.25576,  //  8 tropics
    0.13932,  //  9 field
    0.11957,  // 10 shore
    0.19804,  // 11 rock
    0.09975,  // 12 road
    0.13932,  // 13 waterbed
    0.13932   // 14 field_v
);

// Grain frequency in cycles per metre (= 1/micro_m).
const float kGroundGrainFreq[15] = float[15](
    20.00000,  //  0 tundra
    25.00000,  //  1 taiga
    16.66667,  //  2 snow
    20.00000,  //  3 valley
    25.00000,  //  4 meadow
    20.00000,  //  5 swamp
    33.33333,  //  6 desert
    25.00000,  //  7 steppe
    25.00000,  //  8 tropics
    25.00000,  //  9 field
    33.33333,  // 10 shore
    16.66667,  // 11 rock
    33.33333,  // 12 road
    20.00000,  // 13 waterbed
    25.00000   // 14 field_v
);

// How far this ground's own margin wanders into its neighbour,
// in metres — the amplitude of mesh.frag's second material
// sample. A built thing (a road) keeps a small number and stays
// crisp; sand creeps with a large one.
const float kGroundEdge[15] = float[15](
    1.00000,  //  0 tundra
    1.20000,  //  1 taiga
    1.50000,  //  2 snow
    1.00000,  //  3 valley
    1.00000,  //  4 meadow
    1.40000,  //  5 swamp
    1.60000,  //  6 desert
    1.00000,  //  7 steppe
    1.20000,  //  8 tropics
    0.40000,  //  9 field
    1.60000,  // 10 shore
    1.20000,  // 11 rock
    0.30000,  // 12 road
    1.00000,  // 13 waterbed
    0.40000   // 14 field_v
);

// How much this ground darkens inside the shoreline height band.
const float kGroundDamp[15] = float[15](
    0.00000,  //  0 tundra
    0.00000,  //  1 taiga
    0.00000,  //  2 snow
    0.00000,  //  3 valley
    0.00000,  //  4 meadow
    0.60000,  //  5 swamp
    0.00000,  //  6 desert
    0.00000,  //  7 steppe
    0.00000,  //  8 tropics
    0.00000,  //  9 field
    1.00000,  // 10 shore
    0.00000,  // 11 rock
    0.00000,  // 12 road
    1.00000,  // 13 waterbed
    0.00000   // 14 field_v
);

// RGB axis the hue drift travels along (>1 warms a channel).
const vec3 kGroundChromaAxis[15] = vec3[15](
    vec3(1.05000, 1.00000, 0.90000),  //  0 tundra
    vec3(0.90000, 1.10000, 0.85000),  //  1 taiga
    vec3(1.00000, 1.00000, 1.05000),  //  2 snow
    vec3(1.10000, 1.00000, 0.80000),  //  3 valley
    vec3(1.00000, 1.10000, 0.80000),  //  4 meadow
    vec3(0.95000, 1.05000, 0.85000),  //  5 swamp
    vec3(1.05000, 1.00000, 0.85000),  //  6 desert
    vec3(1.05000, 1.00000, 0.85000),  //  7 steppe
    vec3(0.90000, 1.15000, 0.85000),  //  8 tropics
    vec3(1.10000, 1.00000, 0.80000),  //  9 field
    vec3(1.05000, 1.00000, 0.90000),  // 10 shore
    vec3(1.00000, 1.00000, 1.00000),  // 11 rock
    vec3(1.05000, 1.00000, 0.90000),  // 12 road
    vec3(0.95000, 1.00000, 1.05000),  // 13 waterbed
    vec3(1.10000, 1.00000, 0.80000)   // 14 field_v
);

// x = cover row id (0 = bare), y = density on this ground.
const vec2 kGroundCover[15] = vec2[15](
    vec2(1.00000, 0.35000),  //  0 tundra
    vec2(1.00000, 0.60000),  //  1 taiga
    vec2(2.00000, 1.00000),  //  2 snow
    vec2(1.00000, 0.45000),  //  3 valley
    vec2(1.00000, 0.75000),  //  4 meadow
    vec2(1.00000, 0.50000),  //  5 swamp
    vec2(0.00000, 0.00000),  //  6 desert
    vec2(1.00000, 0.50000),  //  7 steppe
    vec2(1.00000, 0.90000),  //  8 tropics
    vec2(1.00000, 0.25000),  //  9 field
    vec2(0.00000, 0.00000),  // 10 shore
    vec2(3.00000, 0.18000),  // 11 rock
    vec2(0.00000, 0.00000),  // 12 road
    vec2(0.00000, 0.00000),  // 13 waterbed
    vec2(1.00000, 0.25000)   // 14 field_v
);

// cover 0 none
//    the absence of cover — density is ignored, the ground is bare
// cover 1 grass
//    the first instance: upright blades that bend with the same wind the
//    clouds ride
// cover 2 snow
//    a blanket rather than blades — same function, strands wide and flat,
//    wind zero
// cover 3 moss
//    fine felt in the cracks of stone; too low to sway

// Mean linear colour of each cover layer.
const vec3 kCoverColour[4] = vec3[4](
    vec3(1.00000, 1.00000, 1.00000),  //  0 none
    vec3(0.27000, 0.40000, 0.16000),  //  1 grass
    vec3(0.90000, 0.93000, 0.98000),  //  2 snow
    vec3(0.24000, 0.36000, 0.18000)   //  3 moss
);

// x = strands per metre, y = layer height in metres,
// z = wind response, w = lognormal sigma of the cover's own
// luminance. The strand SLOPE — what tilts the normal — is
// the product y*x, never a fourth number to keep in step.
const vec4 kCoverParams[4] = vec4[4](
    vec4(0.00000, 0.00000, 0.00000, 0.00000),  //  0 none
    vec4(7.00000, 0.28000, 1.00000, 0.25576),  //  1 grass
    vec4(2.50000, 0.10000, 0.00000, 0.07987),  //  2 snow
    vec4(14.00000, 0.03000, 0.00000, 0.17857)   //  3 moss
);

#endif // TIMAERT_GROUND_SURFACE
