// GENERATED by tools/gen_prop_profiles.py from
// data/prop_profiles.csv — do not hand-edit. Edit the CSV and
// re-run; `prop_profile_test` re-derives this file and fails on
// drift.
//
// A profile is a BODY OF REVOLUTION given by rings: `segments`
// sides around the axis, and for each ring the radius it stands at
// (fraction of half-width) and the height it stands on (fraction of
// height). The vertex stage builds quads between neighbouring rings
// and closes the top with a fan; a ring of radius 0 collapses its
// quads into triangles on its own, so a cone needs no branch.
#ifndef TIMAERT_PROP_PROFILES
#define TIMAERT_PROP_PROFILES

const uint kProfileCount = 2u;
const uint kProfileMaxRings = 6u;

// 0 tree_near — 6 segments, 5 rings, 162 vertices
//    THE tree of the 3×3 window: a tapering trunk, a crown that flares
//    off it and closes to a point. Five rings is the fewest that still
//    reads as a tree rather than as a lollipop — the flare at 0.42 is
//    what makes a silhouette a crown, and the 0.46 waist above it keeps
//    the top from looking like a cone on a stick. 6 segments × 4 ring
//    gaps + cap = 162 vertices, 54 triangles
// 1 tree_far — 4 segments, 4 rings, 84 vertices
//    THE same tree seen from far enough that facets and waist are below a
//    pixel: one flare, one point, four sides. 4 × 3 + cap = 84 vertices,
//    28 triangles — the LOD rung of the near row, and it is a ROW rather
//    than a branch precisely so the switch is a choice of profile, never
//    a second law of what a tree is

// Sides around the axis.
const uint kProfileSegments[2] = uint[2](
    6u,  // 0 tree_near
    4u   // 1 tree_far
);

// How many rings each profile actually uses.
const uint kProfileRingCount[2] = uint[2](
    5u,  // 0 tree_near
    4u   // 1 tree_far
);

// Where the trunk ends and the crown begins, as a height
// fraction — one number instead of a second material, the same
// way a house splits wall from roof by vLocalY.
const float kProfileBarkTop[2] = float[2](
    0.38000,  // 0 tree_near
    0.34000   // 1 tree_far
);

// The trunk's own colour. The CROWN's is not here: it is the
// cover row `canopy` (ground_surface.glsl), which the far sheet
// reads too — one wood seen at two distances, one colour.
const vec3 kProfileBark[2] = vec3[2](
    vec3(0.19000, 0.13000, 0.09000),  // 0 tree_near
    vec3(0.19000, 0.13000, 0.09000)   // 1 tree_far
);

// The rings themselves, PADDED to the cap so the stride is a
// compile-time constant: profile p, ring k is index
// p * kProfileMaxRings + k. x = radius fraction, y = height
// fraction. Padding repeats the last ring, so an over-read
// degenerates instead of reaching into the next profile.
const vec2 kProfileRings[12] = vec2[12](
    vec2(0.11000, 0.00000),  // 0 tree_near ring 0
    vec2(0.07500, 0.36000),  // 0 tree_near ring 1
    vec2(0.52000, 0.42000),  // 0 tree_near ring 2
    vec2(0.46000, 0.72000),  // 0 tree_near ring 3
    vec2(0.00000, 1.00000),  // 0 tree_near ring 4
    vec2(0.00000, 1.00000),  // 0 tree_near ring 5
    vec2(0.10000, 0.00000),  // 1 tree_far ring 0
    vec2(0.09000, 0.34000),  // 1 tree_far ring 1
    vec2(0.50000, 0.40000),  // 1 tree_far ring 2
    vec2(0.00000, 1.00000),  // 1 tree_far ring 3
    vec2(0.00000, 1.00000),  // 1 tree_far ring 4
    vec2(0.00000, 1.00000)   // 1 tree_far ring 5
);

#endif // TIMAERT_PROP_PROFILES
