# Regenerates git_hash.h on EVERY build (a custom target runs this script),
# so the menu footer names the commit actually built — a configure-time
# variable would silently go stale between commits. Writes only on change,
# so an unchanged hash does not retrigger compilation.
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE _hash
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)
if(NOT _hash)
    set(_hash "unknown")
endif()
execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE _dirty
    ERROR_QUIET)
if(NOT _dirty STREQUAL "")
    set(_hash "${_hash}+")
endif()
set(_content "// Generated by cmake/git_hash.cmake — do not edit.
#pragma once
#define TIMAERT_GIT_HASH \"${_hash}\"
")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
else()
    set(_old "")
endif()
if(NOT _content STREQUAL _old)
    file(WRITE "${OUT}" "${_content}")
endif()
